#!/bin/bash

PROG_NAME=$(basename $0)
DIR_NAME=$(dirname $0)

# ====== Functions decls & common initializations  ======

. $DIR_NAME/functions.rc
. $DIR_NAME/download-common.rc

# ====== main block of code ======

if [ -d "$target" -a -d "$ccTarget" ]; then
  download zakladni-prehled ${DISEASE_URL_BASE}/zakladni-prehled csv false $downloadMeta
  download osoby ${DISEASE_URL_BASE}/osoby csv false $downloadMeta
  download vyleceni ${DISEASE_URL_BASE}/vyleceni csv false $downloadMeta
  download umrti ${DISEASE_URL_BASE}/umrti csv false $downloadMeta
  download hospitalizace ${DISEASE_URL_BASE}/hospitalizace csv true $downloadMeta           # copy
  download nakazeni-vyleceni-umrti-testy ${DISEASE_URL_BASE}/nakazeni-vyleceni-umrti-testy csv true $downloadMeta           # copy
  download kraj-okres-nakazeni-vyleceni-umrti ${DISEASE_URL_BASE}/kraj-okres-nakazeni-vyleceni-umrti csv false $downloadMeta
  download orp ${DISEASE_URL_BASE}/orp csv false $downloadMeta
  download obce ${DISEASE_URL_BASE}/obce csv false $downloadMeta
  download mestske-casti ${DISEASE_URL_BASE}/mestske-casti csv false $downloadMeta
  download incidence-7-14-cr ${DISEASE_URL_BASE}/incidence-7-14-cr csv false $downloadMeta
  download incidence-7-14-kraje ${DISEASE_URL_BASE}/incidence-7-14-kraje csv false $downloadMeta
  download incidence-7-14-okresy ${DISEASE_URL_BASE}/incidence-7-14-okresy csv false $downloadMeta
  download nakazeni-reinfekce ${DISEASE_URL_BASE}/nakazeni-reinfekce csv true $downloadMeta           # copy
  download nakazeni-hospitalizace-testy ${DISEASE_URL_BASE}/nakazeni-hospitalizace-testy csv false $downloadMeta
  download prehled-reinfekce ${DISEASE_URL_BASE}/prehled-reinfekce csv false $downloadMeta
  download pozitivni-pripady ${DISEASE_URL_BASE}/pozitivni-pripady csv false $downloadMeta
  download nakazeni-reinfekce-tyden ${DISEASE_URL_BASE}/nakazeni-reinfekce-tyden csv false $downloadMeta
  download reinfekce-denni-prehled ${DISEASE_URL_BASE}/reinfekce-denni-prehled csv false $downloadMeta
  
  download testy-pcr-antigenni ${DISEASE_URL_BASE}/testy-pcr-antigenni csv false $downloadMeta
  download kraj-okres-testy ${DISEASE_URL_BASE}/kraj-okres-testy csv false $downloadMeta
  download prehled-odberovych-mist ${DISEASE_URL_BASE}/prehled-odberovych-mist csv false $downloadMeta
  download testy-kraje ${DISEASE_URL_BASE}/testy-kraje csv false $downloadMeta
  
  download ockovani ${DISEASE_URL_BASE}/ockovani csv false $downloadMeta
  download ockovaci-mista ${DISEASE_URL_BASE}/ockovaci-mista csv false $downloadMeta
  download prehled-ockovacich-mist ${DISEASE_URL_BASE}/prehled-ockovacich-mist csv false $downloadMeta
  download ockovani-distribuce-sklad ${DISEASE_URL_BASE}/ockovani-distribuce-sklad csv false $downloadMeta
  download ockovani-registrace ${DISEASE_URL_BASE}/ockovani-registrace csv false $downloadMeta
  download ockovani-rezervace ${DISEASE_URL_BASE}/ockovani-rezervace csv false $downloadMeta
  download ockovani-profese ${DISEASE_URL_BASE}/ockovani-profese csv link $downloadMeta                     # link temporary to target
  download ockovani-demografie ${DISEASE_URL_BASE}/ockovani-demografie csv false $downloadMeta
  download ockovani-geografie ${DISEASE_URL_BASE}/ockovani-geografie csv false $downloadMeta
  download ockovaci-zarizeni ${DISEASE_URL_BASE}/ockovaci-zarizeni csv false $downloadMeta
  download ockovani-zakladni-prehled ${DISEASE_URL_BASE}/ockovani-zakladni-prehled csv false $downloadMeta
  download ockovani-pozitivni ${DISEASE_URL_BASE}/ockovani-pozitivni csv false $downloadMeta
  download ockovani-pozitivni65 ${DISEASE_URL_BASE}/ockovani-pozitivni65 csv false $downloadMeta
  download ockovani-umrti ${DISEASE_URL_BASE}/ockovani-umrti csv false $downloadMeta
  download ockovani-hospitalizace ${DISEASE_URL_BASE}/ockovani-hospitalizace csv false $downloadMeta
  download ockovani-jip ${DISEASE_URL_BASE}/ockovani-jip csv false $downloadMeta
  download ockovani-pozitivni-tyden ${DISEASE_URL_BASE}/ockovani-pozitivni-tyden csv false $downloadMeta
  download ockovani-hospitalizace-tyden ${DISEASE_URL_BASE}/ockovani-hospitalizace-tyden csv false $downloadMeta
  download ockovani-jip-tyden ${DISEASE_URL_BASE}/ockovani-jip-tyden csv false $downloadMeta
  download ockovani-orp ${DISEASE_URL_BASE}/ockovani-orp csv false $downloadMeta
  download ockovani-pozitivni-hospitalizovani ${DISEASE_URL_BASE}/ockovani-pozitivni-hospitalizovani csv false $downloadMeta
  
  download pomucky ${DISEASE_URL_BASE}/pomucky csv false false
  
  download kapacity-intenzivni-pece-zdravotnicke-zarizeni-10-2021 ${DIP_URL_BASE}/kapacity-intenzivni-pece-zdravotnicke-zarizeni-10-2021 csv false $downloadMeta
  
  # 'obce' in old format
  downloadSimple https://share.uzis.cz/s/dCZBiARJ27ayeoS/download $target/obce-$(getTstmp).zip obce.zip
  
  # download and copy PES-data
  pesDest=$target/pes-data-$(getTstmp).zip
  downloadSimple https://share.uzis.cz/s/BRfppYFpNTddAy4/download $pesDest pes-data.zip
  unzip -o $pesDest -d $ccTarget >> $logFile
  
  # 'incidence' in old format
  downloadSimple https://share.uzis.cz/s/sFMHoDD2SK7AbXW/download $target/web-pozitivni-$(getTstmp).zip web-pozitivni.zip
  
  # download copy of demographics data (origin: CZSO)
  downloadSimple https://share.uzis.cz/s/KKsz8yTL5HpngDi/download $target/demografie-$(getTstmp).zip demografie.zip
  
  echo "" >> $logFile
  echo "Download finished with cumulative errCode: $cumulativeCode." >> $logFile
else
  errTargets
fi
