#!/bin/bash

PROG_NAME=$(basename $0)
DIR_NAME=$(dirname $0)

# ====== Functions decls & common initializations  ======

. $DIR_NAME/functions.rc
. $DIR_NAME/download-common.rc

# ====== main block of code ======

if [ -d "$target" -a -d "$ccTarget" ]; then
#   downloadCouple zakladni-prehled ${DISEASE_URL_BASE}/zakladni-prehled true false $downloadMeta
#   downloadCouple osoby ${DISEASE_URL_BASE}/osoby true false $downloadMeta
#   downloadCouple nakaza ${DISEASE_URL_BASE}/nakaza true false $downloadMeta
#   downloadCouple vyleceni ${DISEASE_URL_BASE}/vyleceni true false $downloadMeta
#   downloadCouple umrti ${DISEASE_URL_BASE}/umrti true false $downloadMeta
#   downloadCouple hospitalizace ${DISEASE_URL_BASE}/hospitalizace true true $downloadMeta           # copy
#   downloadCouple nakazeni-vyleceni-umrti-testy ${DISEASE_URL_BASE}/nakazeni-vyleceni-umrti-testy true true $downloadMeta         # copy
#   downloadCouple kraj-okres-nakazeni-vyleceni-umrti ${DISEASE_URL_BASE}/kraj-okres-nakazeni-vyleceni-umrti true false $downloadMeta
#   downloadCouple orp ${DISEASE_URL_BASE}/orp true false $downloadMeta
#   downloadCouple obce ${DISEASE_URL_BASE}/obce false false $downloadMeta
#   downloadCouple mestske-casti ${DISEASE_URL_BASE}/mestske-casti true false $downloadMeta
#   downloadCouple incidence-7-14-cr ${DISEASE_URL_BASE}/incidence-7-14-cr true false $downloadMeta
#   downloadCouple incidence-7-14-kraje ${DISEASE_URL_BASE}/incidence-7-14-kraje true false $downloadMeta
#   download incidence-7-14-okresy ${DISEASE_URL_BASE}/incidence-7-14-okresy csv false $downloadMeta
#   download nic http://localhost/badurl csv
  
#   downloadCouple testy ${DISEASE_URL_BASE}/testy true false $downloadMeta
#   downloadCouple testy-pcr-antigenni ${DISEASE_URL_BASE}/testy-pcr-antigenni true false $downloadMeta
#   downloadCouple kraj-okres-testy ${DISEASE_URL_BASE}/kraj-okres-testy true false $downloadMeta
#   downloadCouple prehled-odberovych-mist ${DISEASE_URL_BASE}/prehled-odberovych-mist true false $downloadMeta
  
#   downloadCouple ockovani ${DISEASE_URL_BASE}/ockovani true true $downloadMeta                     # copy
#   downloadCouple ockovaci-mista ${DISEASE_URL_BASE}/ockovaci-mista false false $downloadMeta
#   downloadCouple prehled-ockovacich-mist ${DISEASE_URL_BASE}/prehled-ockovacich-mist true false $downloadMeta
#   downloadCouple ockovani-spotreba ${DISEASE_URL_BASE}/ockovani-spotreba true false $downloadMeta
#   downloadCouple ockovani-distribuce ${DISEASE_URL_BASE}/ockovani-distribuce true false $downloadMeta
#   download ockovani-distribuce ${DISEASE_URL_BASE}/ockovani-distribuce csv false $downloadMeta
#   downloadCouple ockovani-distribuce-sklad ${DISEASE_URL_BASE}/ockovani-distribuce-sklad true false $downloadMeta
#   downloadCouple ockovani-registrace ${DISEASE_URL_BASE}/ockovani-registrace false false $downloadMeta
#   downloadCouple ockovani-rezervace ${DISEASE_URL_BASE}/ockovani-rezervace true false $downloadMeta
#   downloadCouple ockovani-profese ${DISEASE_URL_BASE}/ockovani-profese false false $downloadMeta
#   download ockovani-profese ${DISEASE_URL_BASE}/ockovani-profese min.json false
#   downloadCouple ockovaci-zarizeni ${DISEASE_URL_BASE}/ockovaci-zarizeni true false $downloadMeta
#   downloadCouple prioritni-skupiny ${DISEASE_URL_BASE}/prioritni-skupiny true false $downloadMeta
  
#   downloadCouple pomucky ${DISEASE_URL_BASE}/pomucky true false $downloadMeta
#   
#   download kapacity-intenzivni-pece-vlna-2 ${DIP_URL_BASE}/kapacity-intenzivni-pece-vlna-2 csv false $downloadMeta
#   download kapacity-intenzivni-pece-zdravotnicke-zarizeni ${DIP_URL_BASE}/kapacity-intenzivni-pece-zdravotnicke-zarizeni csv false $downloadMeta
#   download kapacity-intenzivni-pece-zdravotnicke-zarizeni-04-2021 ${DIP_URL_BASE}/kapacity-intenzivni-pece-zdravotnicke-zarizeni-04-2021 csv false $downloadMeta

#   # 'obce' in old format
#   downloadSimple https://share.uzis.cz/s/dCZBiARJ27ayeoS/download $target/obce-$(getTstmp).zip obce.zip
  
  # download and copy PES-data
  pesDest=$target/pes-data-$(getTstmp).zip
  downloadSimple https://share.uzis.cz/s/BRfppYFpNTddAy4/download $pesDest pes-data.zip
  unzip -o $pesDest -d $ccTarget >> $logFile
  
#   # 'incidence' in old format
#   downloadSimple https://share.uzis.cz/s/sFMHoDD2SK7AbXW/download $target/web-pozitivni-$(getTstmp).zip web-pozitivni.zip
#   
#   # download copy of demographics data (origin: CZSO)
#   downloadSimple https://share.uzis.cz/s/KKsz8yTL5HpngDi/download $target/demografie-$(getTstmp).zip demografie.zip
:
else
  if [ -d "$target" ]; then
    echo "'cc-target' dir $ccTarget doesn't exist!" >&2
  else
    echo "'target' dir $target doesn't exist!" >&2
  fi
  
  errUsage
  exit 2
fi

#   wget -O $target/-$(getTstmp).csv 
#   wget -O $target/-$(getTstmp).json 

#   wget -O $target/testy-pcr-antigenni-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/testy-pcr-antigenni.csv
#   wget -O $target/testy-pcr-antigenni-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/testy-pcr-antigenni.json
#   wget -O $target/testy-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/testy.csv
#   wget -O $target/testy-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/testy.json
#   wget -O $target/kraj-okres-testy-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/kraj-okres-testy.csv
#   wget -O $target/kraj-okres-testy-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/kraj-okres-testy.json
#   wget -O $target/nakaza-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/nakaza.csv
#   wget -O $target/nakaza-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/nakaza.json
#   wget -O $target/nakazeni-vyleceni-umrti-testy-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/nakazeni-vyleceni-umrti-testy.csv
#   wget --progress=bar:force:noscroll -O $target/nakazeni-vyleceni-umrti-testy-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/nakazeni-vyleceni-umrti-testy.json 2>> $logFile
#   wget -nv --progress=bar:force:noscroll --show-progress -O $target/zakladni-prehled-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/zakladni-prehled.csv 2>> $logFile
#   wget -O $target/zakladni-prehled-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/zakladni-prehled.json
#   wget -O $target/orp-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/orp.csv
#   wget -O $target/orp-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/orp.json
#   wget -O $target/obce-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/obce.csv
#   wget -O $target/obce-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/obce.json
#   wget --progress=dot:giga -O $target/osoby-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/osoby.csv 2>> $logFile
#   wget -O $target/osoby-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/osoby.json
#   wget -O $target/kraj-okres-nakazeni-vyleceni-umrti-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/kraj-okres-nakazeni-vyleceni-umrti.csv
#   wget -O $target/kraj-okres-nakazeni-vyleceni-umrti-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/kraj-okres-nakazeni-vyleceni-umrti.json
#   wget -O $target/vyleceni-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/vyleceni.csv
#   wget -O $target/vyleceni-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/vyleceni.json
#   wget -O $target/umrti-$(getTstmp).csv https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/umrti.csv
#   wget -O $target/umrti-$(getTstmp).json https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/umrti.json
# #   wget -O $target/mestske-casti-$(getTstmp).csv "https://share.uzis.cz/s/dCZBiARJ27ayeoS/download?path=/&files=mestske-casti.csv"
# #   wget -O $target/obec-$(getTstmp).csv "https://share.uzis.cz/s/dCZBiARJ27ayeoS/download?path=%2F&files=obec.csv"
# #   wget -O $target/obce-$(getTstmp).zip https://share.uzis.cz/s/dCZBiARJ27ayeoS/download?path=%2F
#   wget -O $target/obce-$(getTstmp).zip https://share.uzis.cz/s/dCZBiARJ27ayeoS/download
#   wget -O $target/pes-data-$(getTstmp).zip https://share.uzis.cz/s/BRfppYFpNTddAy4/download
